sample<-read.table("household_power_consumption.txt",header=TRUE,nrows=100)
classes<-sapply(sample,class)
table<-read.table("household_power_consumption.txt",header=TRUE,sep=";",colClasses=classes,na.strings="?")
table$Date<-as.Date(table$Date,"%d/%m/%Y")
subtable<-subset(table,(table$Date== as.Date("2007-02-01") | table$Date == as.Date("2007-02-02")))
subtable$datetime<-as.POSIXct(paste(subtable$Date,subtable$Time),format="%Y-%m-%d %H:%M:%S")
png(filename="plot2.png")
with(subtable,plot(datetime,Global_active_power,type="l",ylab="Global Active Power(killowatts)",xlab=NA))
dev.off()