sample<-read.table("household_power_consumption.txt",header=TRUE,nrows=100)
classes<-sapply(sample,class)
table<-read.table("household_power_consumption.txt",header=TRUE,sep=";",colClasses=classes,na.strings="?")
table$Date<-as.Date(table$Date,"%d/%m/%Y")
subtable<-subset(table,(table$Date== as.Date("2007-02-01") | table$Date == as.Date("2007-02-02")))
subtable$datetime<-as.POSIXct(paste(subtable$Date,subtable$Time),format="%Y-%m-%d %H:%M:%S")
png(filename="plot4.png")
par(mfcol=c(2,2))
with(subtable,plot(datetime,Global_active_power,type="l",ylab="Global Active Power",xlab=NA))
with(subtable,plot(datetime,Sub_metering_1,type="l",ylab="Energy sub metering",xlab=NA))
with(subtable,lines(datetime,Sub_metering_2,col="red"))
with(subtable,lines(datetime,Sub_metering_3,col="blue"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1,lty=c(1,1),cex=0.5)
with(subtable,plot(datetime,Voltage,type="l",ylab="Voltage"))
with(subtable,plot(datetime,Global_reactive_power,type="l",ylab="Global_reactive_power"))
dev.off()